/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desenvsoftware.formcadastroaluno;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author hermes
 */
public class FormularioCadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioCadastro.class.getName());

    /**
     * Creates new form FormularioCadastro
     */
   public char sexo;
   private static final String nomeArquivo = "alunos";
   public List<Aluno> listaAlunos = new ArrayList<>();

   public List<Aluno> leArquivo() {

      listaAlunos.clear();

      try (BufferedReader leitor = new BufferedReader(new FileReader(nomeArquivo + ".txt"))) {

          String linha;

          while ((linha = leitor.readLine()) != null) {

              if (linha.isBlank()) {
                  continue;
              }

              String[] campos = linha.split(";");

              if (campos.length < 10) {
                  System.out.println("Linha ignorada (formato inválido): " + linha);
                  continue;
              }

              String nome = campos[0];
              char sexo = campos[1].charAt(0);
              String dataNascimento = campos[2];
              String CPF = campos[3];
              String Matricula = campos[4];
              String endereco = campos[5];
              String curso = campos[6];
              String CEP = campos[7];
              String telefone = campos[8];
              String estado = campos[9];

              var A = new Aluno(nome, sexo, dataNascimento, CPF, Matricula, endereco, curso, CEP, telefone, estado);

              listaAlunos.add(A);
              
              
          }

      } catch (FileNotFoundException e) {
          // Arquivo ainda não existe
          // Lista permanece vazia
         System.out.println("Arquivo ainda não existe");

      } catch (IOException e) {

          e.printStackTrace();
      }

      return listaAlunos;
   }

   public List<Aluno> getListaAlunos(){
       return listaAlunos;
   }

   public void gravaArquivo(){

   try (BufferedWriter escritor = new BufferedWriter(new FileWriter(nomeArquivo + ".txt", false))) {

       for (Aluno A : listaAlunos) {

           escritor.write(
               A.nome + ";" +
               A.sexo + ";" +
               A.dataNascimento + ";" +
               A.CPF + ";" +
               A.Matricula + ";" +
               A.endereco + ";" +
               A.curso + ";" +
               A.CEP + ";" +
               A.telefone + ";" +
               A.estado
           );

           escritor.newLine();
       }

       System.out.println("Lista salva no arquivo");

   } catch (IOException e) {

   e.printStackTrace();
   }


   }


    public FormularioCadastro() {
        initComponents();
        listaAlunos = leArquivo();
        carregarTabela();
    }
    
    /**
     * carrega tabela no formulário
     */
    public void carregarTabela() {
    
    DefaultTableModel tabela = (DefaultTableModel) tbl_Alunos.getModel();
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgsexo = new javax.swing.ButtonGroup();
        lblNomeCompleto = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        TxaNomeCompleto = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        TxaCpf = new javax.swing.JTextField();
        TxaData = new javax.swing.JTextField();
        TxaCurso = new javax.swing.JTextField();
        TxaCep = new javax.swing.JTextField();
        TxaEndereco = new javax.swing.JTextField();
        TxaMatricula = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxaCampo = new javax.swing.JTextArea();
        lblCpf1 = new javax.swing.JLabel();
        TxaTelefone = new javax.swing.JTextField();
        btFormulario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Alunos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomeCompleto.setText("Nome completo:");

        lblDataNascimento.setText("Data de Nascimento:");

        lblSexo.setText("Sexo:");

        lblMatricula.setText("Matrícula:");

        lblCurso.setText("Curso:");

        lblCpf.setText("CPF:");

        lblEndereco.setText("Endereço:");

        lblCep.setText("CEP:");

        lblEstado.setText("Estado:");

        TxaNomeCompleto.addActionListener(this::TxaNomeCompletoActionPerformed);

        bgsexo.add(rbMasculino);
        rbMasculino.setSelected(true);
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(this::rbMasculinoActionPerformed);

        bgsexo.add(rbFeminino);
        rbFeminino.setText("Feminino");
        rbFeminino.addActionListener(this::rbFemininoActionPerformed);

        TxaCpf.setToolTipText("");

        TxaData.setToolTipText("");
        TxaData.setActionCommand("<Not Set>");

        TxaCurso.setToolTipText("");
        TxaCurso.setActionCommand("<Not Set>");

        TxaCep.setToolTipText("");
        TxaCep.setActionCommand("<Not Set>");

        TxaEndereco.setToolTipText("");
        TxaEndereco.setActionCommand("<Not Set>");
        TxaEndereco.addActionListener(this::TxaEnderecoActionPerformed);

        TxaMatricula.setToolTipText("");
        TxaMatricula.setActionCommand("<Not Set>");
        TxaMatricula.addActionListener(this::TxaMatriculaActionPerformed);

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        TxaCampo.setColumns(20);
        TxaCampo.setRows(5);
        jScrollPane1.setViewportView(TxaCampo);

        lblCpf1.setText("Telefone:");

        TxaTelefone.setToolTipText("");
        TxaTelefone.setActionCommand("<Not Set>");
        TxaTelefone.addActionListener(this::TxaTelefoneActionPerformed);

        btFormulario.setText("Enviar");
        btFormulario.addActionListener(this::btFormularioActionPerformed);

        tbl_Alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Sexo", "DataNascimento", "CPF", "Matricula", "Endereco", "Curso", "CEP", "Telefone", "Estado"
            }
        ));
        jScrollPane2.setViewportView(tbl_Alunos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEstado)
                                    .addGap(316, 316, 316))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TxaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxaCurso))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCpf1)
                                        .addComponent(lblCep)
                                        .addComponent(lblMatricula)
                                        .addComponent(TxaCep, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TxaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeCompleto)
                                .addGap(147, 147, 147)
                                .addComponent(lblSexo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxaNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbMasculino))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCpf)
                                        .addComponent(TxaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFeminino))
                            .addComponent(lblCurso)
                            .addComponent(lblEndereco)
                            .addComponent(lblDataNascimento)
                            .addComponent(TxaData, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(btFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCompleto)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxaNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbMasculino)
                    .addComponent(rbFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento)
                    .addComponent(lblCpf)
                    .addComponent(lblCpf1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(lblMatricula))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(lblCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxaCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btFormulario)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxaNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxaNomeCompletoActionPerformed
    }//GEN-LAST:event_TxaNomeCompletoActionPerformed

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void rbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemininoActionPerformed

    private void TxaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxaMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxaMatriculaActionPerformed

    private void TxaEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxaEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxaEnderecoActionPerformed

    private void TxaTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxaTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxaTelefoneActionPerformed

    private void btFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFormularioActionPerformed
        
        
        
        
        
        if(rbMasculino.isSelected()) {
                      
                    sexo = 'M';
//                    JOptionPane.showMessageDialog(null,"Sexo masculino selecionado"," ",JOptionPane.OK_OPTION);
                    
                   var A = new Aluno(
                                    TxaNomeCompleto.getText(),
                                    sexo,
                                    TxaData.getText(),
                                    TxaCpf.getText(),
                                    TxaMatricula.getText(),
                                    TxaEndereco.getText(),
                                    TxaCurso.getText(),
                                    TxaCep.getText(),
                                    TxaTelefone.getText(),
                                    String.valueOf(cbEstado.getSelectedItem())
                                    );
                                    TxaCampo.append(A.toString() + "");
                                    
                                    listaAlunos.add(A);
                                    gravaArquivo();
                                    
                                    DefaultTableModel tabela = (DefaultTableModel) tbl_Alunos.getModel();
                                    tabela.addRow(A.obterDados());
                                    
                                    TxaNomeCompleto.setText(" ");
                                    bgsexo.clearSelection();
                                    TxaData.setText(" ");
                                    TxaCpf.setText(" ");
                                    TxaMatricula.setText(" ");
                                    TxaEndereco.setText(" ");
                                    TxaCurso.setText(" ");
                                    TxaCep.setText(" ");
                                    TxaTelefone.setText(" ");
                                    cbEstado.setSelectedIndex(0);
                    }
                    
                    else if (rbFeminino.isSelected()){
                    
                        sexo = 'F';
//                    JOptionPane.showMessageDialog(null,"Sexo Feminino selecionado", "Alerta", JOptionPane.OK_OPTION ); 
                    
                  var A = new Aluno(
                                    TxaNomeCompleto.getText(),
                                    sexo,
                                    TxaData.getText(),
                                    TxaCpf.getText(),
                                    TxaMatricula.getText(),
                                    TxaEndereco.getText(),
                                    TxaCurso.getText(),
                                    TxaCep.getText(),
                                    TxaTelefone.getText(),
                                    String.valueOf(cbEstado.getSelectedItem())
                                    );
                                    TxaCampo.append(A.toString() + "");
                                    
                                    listaAlunos.add(A);
                                    gravaArquivo();
                                    
                                    DefaultTableModel tabela = (DefaultTableModel) tbl_Alunos.getModel();
                                    tabela.addRow(A.obterDados());
                                    
                                    
                                    TxaNomeCompleto.setText(" ");
                                    bgsexo.clearSelection();
                                    TxaData.setText(" ");
                                    TxaCpf.setText(" ");
                                    TxaMatricula.setText(" ");
                                    TxaEndereco.setText(" ");
                                    TxaCurso.setText(" ");
                                    TxaCep.setText(" ");
                                    TxaTelefone.setText(" ");
                                    cbEstado.setSelectedIndex(0);
                    
                    }
                    
                    else {
                      JOptionPane.showMessageDialog(null,"Selecione um sexo","Erro", JOptionPane.ERROR);
                    }
    }//GEN-LAST:event_btFormularioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioCadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxaCampo;
    private javax.swing.JTextField TxaCep;
    private javax.swing.JTextField TxaCpf;
    private javax.swing.JTextField TxaCurso;
    private javax.swing.JTextField TxaData;
    private javax.swing.JTextField TxaEndereco;
    private javax.swing.JTextField TxaMatricula;
    private javax.swing.JTextField TxaNomeCompleto;
    private javax.swing.JTextField TxaTelefone;
    private javax.swing.ButtonGroup bgsexo;
    private javax.swing.JButton btFormulario;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpf1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTable tbl_Alunos;
    // End of variables declaration//GEN-END:variables
}
